### ISSUE TITLE
why RegistryCI dependency?

### ISSUE THREAD

**Issue by ericphanson** [jerjorg/SymmetryReduceBZ.jl#1]
I saw via https://juliahub.com/ui/Packages/RegistryCI/70yP4/6.3.1?t=2 that this package depends on RegistryCI as a test-time dependency, but I couldn't see it being used anywhere. Is that a mistake?

**Comment by jerjorg** [comment]
Yes, this was a mistake, and I removed the dependency from the latest version. Will the dependency automatically be removed from JuliaHub?

**Comment by ericphanson** [comment]
Yes, I think it should! Thanks :)
