### ISSUE TITLE
Installation error on Macs with Arm processors

### ISSUE THREAD

**Issue by tpolakovic** [jerjorg/SymmetryReduceBZ.jl#3]
This is because `BinaryProvider` (dependency in the old `CDDLib`) is not compatible with the new architecture and, by the looks of it, not being actively developed. Bumping up the compats of `CDDLib` to 0.9 and `Polyhedra` to 0.7 resolves the issue.

I can make a PR if you want.

**Comment by jerjorg** [comment]
That would be great!
